### ISSUE TITLE
selfunverify is not toy

### ISSUE THREAD

**Issue by Redak37** [Misha12/GrillBot#266]
Navrhuji, aby minimální doba pro selfunverify zohledňovala kolikrát si již člověk dal selfunverify, pokud má někdo 100+ použití, tak jsou pro něj 2 hodiny zřejmě málo a dává si je opakovaně hned po skončení, navrhuji algoritmus (2 + (počet použití / 10)) hodin jako minimum.

**Comment by Kuba314** [comment]
je blbost to mít lineárně imho, pro takovouhle situaci je `ln` lepší
![image](https://user-images.githubusercontent.com/35199722/111683127-6aafb680-8825-11eb-8851-49aadbab3257.png)
